// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFtETTu8cF4BRqeTqGFSiSCwS6gsBKY6Y',
    appId: '1:726130596875:android:f1a22646d15e740e4dfb0e',
    messagingSenderId: '726130596875',
    projectId: 'absolute-stone-design-app',
    storageBucket: 'absolute-stone-design-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABTCht006y-pmCSePChf7jVFs7iffKzws',
    appId: '1:726130596875:ios:e908b06e179dfaae4dfb0e',
    messagingSenderId: '726130596875',
    projectId: 'absolute-stone-design-app',
    storageBucket: 'absolute-stone-design-app.firebasestorage.app',
    androidClientId: '726130596875-8gqj5djg0tqp02o2monsirr7j51efmsb.apps.googleusercontent.com',
    iosClientId: '726130596875-q5vuubko2c2a7dkcvudnpdhntompkfgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.absoluteChat',
  );
}
